# Generated by Django 5.0.6 on 2024-06-04 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favouritecountries_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favouritecountry',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(max_length=63, unique=True),
        ),
    ]
