# Generated by Django 5.0.6 on 2024-06-04 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favouritecountries_app', '0002_rename_user_id_favouritecountry_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favouritecountry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='favouritecountries_app.users'),
        ),
    ]
